name: build-check
on:
  pull_request:
    types: [ opened, synchronize, reopened ] # PRのOpen,Reopen,更新時に実行

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }} # PRのヘッドブランチの最新の状態を取得
          submodules: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_BUILD_CHECK }}
        # jdkのセットアップ
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        # Gradleの実行権限を付与
      - name: Make gradlew executable　
        run: chmod +x ./gradlew
        # 全てのビルドバリアントをチェック
      - name: Build With Gradle
        env:
          USERNAME: ${{ secrets.BUILD_GITHUB_USERNAME }}
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_BUILD_CHECK }}
        run: |
          ./gradlew assembleDevelopDebug assembleProductRelease
        timeout-minutes: 30