name: build-release

#手動で実行
on:
  workflow_dispatch:
    inputs:
      # ビルドバリアントを選択
      variant:
        description: 'Build variant'
        required: true
        #ビルドするブランチ名を選択
      ref:
        description: 'branch name|tag name|commit SHA'
        required: true
        default: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} #入力したブランチを取得
      #jdkのセットアップ
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      # Gradleの実行権限を付与
      - name: Make gradlew executable　
        run: chmod +x ./gradlew
        # keystoreのデコード
      - name: Decode Keystore
        run: echo '${{ secrets.RELEASE_KEYSTORE_BASE64 }}' | base64 -d> release.jks
      #入力したbuild variantで署名付きビルド
      - name: Build With Gradle
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: |
          ./gradlew bundle${{ github.event.inputs.variant }}
      # aabファイルのパスを取得
      - name: Get apk path
        id: apk-path
        run: |
          path=$(find **/build/outputs/ -name '*.aab' -type f | head -1)
          echo "path=$path" >> $GITHUB_ENV
      # debugビルドの場合はapkをアップロード
      - name: Upload apk file
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: ${{ env.path }}
          retention-days: 1 # 1日後に削除(ストレージ圧迫対策）
